### ISSUE TITLE
Support IMDSv2 on instance metadata check

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla-manager#3691] opened 2024-01-18 15:17 UTC
### What happened?

Running `scylla-manager-agent check-location` command throws a `failed` log, regardless of the s3 region being explicitly set in the agent's config.

```
$ scylla-manager-agent check-location --debug --location s3:rzetelskik-sa
{"L":"ERROR","T":"2024-01-17T09:56:02.679Z","N":"rclone","M":"parse instance region: invalid character '<' looking for beginning of value","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.RedirectLogPrint.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/logger.go:19\ngithub.com/rclone/rclone/fs.LogPrintf\n\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:152\ngithub.com/rclone/rclone/fs.Errorf\n\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.awsRegionFromMetadataAPI\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/aws.go:42\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.(*S3Options).AutoFill\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/options.go:138\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.RegisterS3Provider\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/providers.go:52\nmain.setupCommand\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/setup.go:35\nmain.glob..func3\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/check_location.go:40\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.1.1/command.go:850\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.1.1/command.go:958\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.1.1/command.go:895\nmain.main\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/main.go:12\nruntime.main\n\truntime/proc.go:250"}
{"L":"INFO","T":"2024-01-17T09:56:02.679Z","N":"rclone","M":"registered s3 provider [name=s3, env_auth=true, disable_checksum=true, memory_pool_flush_time=5m, provider=AWS, chunk_size=50M, memory_pool_use_mmap=true, upload_concurrency=2, no_check_bucket=true]"}
{"L":"INFO","T":"2024-01-17T09:56:02.679Z","N":"rclone","M":"registered gcs provider [name=gcs, bucket_policy_only=true, memory_pool_flush_time=5m, memory_pool_use_mmap=true, chunk_size=50M, allow_create_bucket=false]"}
{"L":"INFO","T":"2024-01-17T09:56:02.679Z","N":"rclone","M":"registered azure provider [name=azure, memory_pool_use_mmap=true, chunk_size=50M, use_msi=true, memory_pool_flush_time=5m, disable_checksum=true]"}
{"L":"DEBUG","T":"2024-01-17T09:56:02.679Z","N":"rclone","M":"Creating backend with remote \"s3:rzetelskik-sa\""}
{"L":"DEBUG","T":"2024-01-17T09:56:02.680Z","N":"rclone","M":"Creating backend with remote \"/tmp/scylla-manager-agent-816026857\""}
{"L":"INFO","T":"2024-01-17T09:56:04.188Z","N":"rclone","M":"S3 bucket rzetelskik-sa: Switched region to \"us-west-1\" from \"us-east-1\""}
{"L":"DEBUG","T":"2024-01-17T09:56:04.188Z","N":"rclone","M":"pacer: low level retry 1/1 (error BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region at endpoint '', bucket is in 'us-west-1' region\n\tstatus code: 301, request id: 7CTC7M7HE0JTVWWW, host id: KsASLPk0DDjWyvBLrKn5j+7QezPp9TqNcCye76TZFa3ov2d/yMzSIxUUDvg5wc/lD5qrNA8GTCI=)"}
{"L":"DEBUG","T":"2024-01-17T09:56:04.188Z","N":"rclone","M":"pacer: Rate limited, increasing sleep to 10ms"}
{"L":"DEBUG","T":"2024-01-17T09:56:04.190Z","N":"rclone","M":"S3 bucket rzetelskik-sa: Waiting for checks to finish"}
{"L":"DEBUG","T":"2024-01-17T09:56:04.190Z","N":"rclone","M":"S3 bucket rzetelskik-sa: Waiting for transfers to finish"}
{"L":"DEBUG","T":"2024-01-17T09:56:04.341Z","N":"rclone","M":"pacer: Reducing sleep to 0s"}
{"L":"DEBUG","T":"2024-01-17T09:56:04.408Z","N":"rclone","M":"scylla-manager-agent-816026857/test: Copied (new)"}
{"L":"DEBUG","T":"2024-01-17T09:56:04.522Z","N":"rclone","M":"Creating backend with remote \"s3:rzetelskik-sa/scylla-manager-agent-816026857\""}
{"L":"INFO","T":"2024-01-17T09:56:05.733Z","N":"rclone","M":"S3 bucket rzetelskik-sa: Switched region to \"us-west-1\" from \"us-east-1\""}
{"L":"DEBUG","T":"2024-01-17T09:56:05.733Z","N":"rclone","M":"pacer: low level retry 1/1 (error BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region at endpoint '', bucket is in 'us-west-1' region\n\tstatus code: 301, request id: 7Y8VMJF3D4F63YFT, host id: GtkEVuRer55t4D9Z0JfyhvdZFxTF3I9ooTTxYQ6jVTHBNJGso0u93FDmvQfXi3ECA6zxhIP8NSE=)"}
{"L":"DEBUG","T":"2024-01-17T09:56:05.733Z","N":"rclone","M":"pacer: Rate limited, increasing sleep to 10ms"}
FAILED: init remote temp dir: BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region at endpoint '', bucket is in 'us-west-1' region
        status code: 301, request id: 7Y8VMJF3D4F63YFT, host id: GtkEVuRer55t4D9Z0JfyhvdZFxTF3I9ooTTxYQ6jVTHBNJGso0u93FDmvQfXi3ECA6zxhIP8NSE=
```

### What did you expect to happen?
`scylla-manager-agent check-location` command shouldn't fail when the instance and bucket are in the same region. Especially when the region is explicitly configured in the agent's config.

### How can we reproduce it?
Run `scylla-manager-agent check-location` in an instance deployed in a region different than  `us-east-1`, e.g. `us-west-1`.

### Scylla Manager version
3.2.5

### Further details
Note that the backup ran successfully, so there weren't any actual connectivity issues.

Also note that the first error message occurs even on successful runs. Below the logs from a command ran in an instance deployed in the "default" region, us-east-1:
```
$ scylla-manager-agent check-location --debug --location s3:rzetelskik-scylladb
{"L":"ERROR","T":"2024-01-18T15:15:27.624Z","N":"rclone","M":"parse instance region: invalid character '<' looking for beginning of value","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.RedirectLogPrint.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/logger.go:19\ngithub.com/rclone/rclone/fs.LogPrintf\n\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:152\ngithub.com/rclone/rclone/fs.Errorf\n\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.awsRegionFromMetadataAPI\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/aws.go:42\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.(*S3Options).AutoFill\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/options.go:138\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.RegisterS3Provider\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/providers.go:52\nmain.setupCommand\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/setup.go:35\nmain.glob..func3\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/check_location.go:40\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.1.1/command.go:850\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.1.1/command.go:958\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.1.1/command.go:895\nmain.main\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/main.go:12\nruntime.main\n\truntime/proc.go:250"}
{"L":"INFO","T":"2024-01-18T15:15:27.625Z","N":"rclone","M":"registered s3 provider [name=s3, memory_pool_use_mmap=true, memory_pool_flush_time=5m, provider=AWS, no_check_bucket=true, upload_concurrency=2, disable_checksum=true, chunk_size=50M, env_auth=true]"}
{"L":"INFO","T":"2024-01-18T15:15:27.625Z","N":"rclone","M":"registered gcs provider [name=gcs, memory_pool_flush_time=5m, memory_pool_use_mmap=true, allow_create_bucket=false, chunk_size=50M, bucket_policy_only=true]"}
{"L":"INFO","T":"2024-01-18T15:15:27.625Z","N":"rclone","M":"registered azure provider [name=azure, chunk_size=50M, use_msi=true, memory_pool_use_mmap=true, memory_pool_flush_time=5m, disable_checksum=true]"}
{"L":"DEBUG","T":"2024-01-18T15:15:27.625Z","N":"rclone","M":"Creating backend with remote \"s3:rzetelskik-scylladb\""}
{"L":"DEBUG","T":"2024-01-18T15:15:27.626Z","N":"rclone","M":"Creating backend with remote \"/tmp/scylla-manager-agent-766329222\""}
{"L":"DEBUG","T":"2024-01-18T15:15:28.023Z","N":"rclone","M":"S3 bucket rzetelskik-scylladb: Waiting for checks to finish"}
{"L":"DEBUG","T":"2024-01-18T15:15:28.024Z","N":"rclone","M":"S3 bucket rzetelskik-scylladb: Waiting for transfers to finish"}
{"L":"DEBUG","T":"2024-01-18T15:15:28.096Z","N":"rclone","M":"scylla-manager-agent-766329222/test: Copied (new)"}
{"L":"DEBUG","T":"2024-01-18T15:15:28.149Z","N":"rclone","M":"Creating backend with remote \"s3:rzetelskik-scylladb/scylla-manager-agent-766329222\""}
{"L":"DEBUG","T":"2024-01-18T15:15:28.264Z","N":"rclone","M":"Waiting for deletions to finish"}
{"L":"DEBUG","T":"2024-01-18T15:15:28.315Z","N":"rclone","M":"test: Deleted"}
```

**Comment by karol-kokoszka** [comment] 2024-02-16 17:16
What I did:
- created the cluster with Scylla-Cloud to have cluster in **us-west-1** and bucket in **us-west-1**
- updated the role assigned to the instance to have the correct access to all buckets in our account
- have another bucket for backups created in region **us-east-1**

State:
- VM in **us-west-1**
- bucket `scylla-cloud-backup-9-9-2vj38h` in **us-east-1*
- bucket `scylla-cloud-backup-10-10-w836gd` in **eu-west-1*

Then having:

**Case #1 (VM and bucket in the same region = us-west-1, no explicit configuration in scylla-manager-agent.yaml)**

- configuration in `/etc/scylla-manager-agent/scylla-manager-agent.yaml ` as follow:
```
auth_token: *****
prometheus: :26090
```
(when the s3 region is not explicitly added to this config sm will use IMDS to find the EC2 instance region and apply it to config)
- `check-location` of the bucket belonging to the same region
```
scyllaadm@ip-172-31-0-200:~$ scylla-manager-agent check-location --debug --location s3:scylla-cloud-backup-10-10-w836gd
{"L":"INFO","T":"2024-02-16T17:07:09.802Z","N":"rclone","M":"registered s3 provider [name=s3, region=us-west-1, upload_concurrency=2, memory_pool_use_mmap=true, env_auth=true, no_check_bucket=true, provider=AWS, chunk_size=50M, memory_pool_flush_time=5m, disable_checksum=true]"}
{"L":"INFO","T":"2024-02-16T17:07:09.802Z","N":"rclone","M":"registered gcs provider [name=gcs, chunk_size=50M, memory_pool_use_mmap=true, memory_pool_flush_time=5m, allow_create_bucket=false, bucket_policy_only=true]"}
{"L":"INFO","T":"2024-02-16T17:07:09.802Z","N":"rclone","M":"registered azure provider [name=azure, chunk_size=50M, memory_pool_use_mmap=true, disable_checksum=true, use_msi=true, memory_pool_flush_time=5m]"}
{"L":"DEBUG","T":"2024-02-16T17:07:09.802Z","N":"rclone","M":"Creating backend with remote \"s3:scylla-cloud-backup-10-10-w836gd\""}
{"L":"DEBUG","T":"2024-02-16T17:07:09.802Z","N":"rclone","M":"Creating backend with remote \"/tmp/scylla-manager-agent-3349653200\""}
{"L":"DEBUG","T":"2024-02-16T17:07:09.856Z","N":"rclone","M":"S3 bucket scylla-cloud-backup-10-10-w836gd: Waiting for checks to finish"}
{"L":"DEBUG","T":"2024-02-16T17:07:09.856Z","N":"rclone","M":"S3 bucket scylla-cloud-backup-10-10-w836gd: Waiting for transfers to finish"}
{"L":"DEBUG","T":"2024-02-16T17:07:09.915Z","N":"rclone","M":"scylla-manager-agent-3349653200/test: Copied (new)"}
{"L":"DEBUG","T":"2024-02-16T17:07:10.035Z","N":"rclone","M":"Creating backend with remote \"s3:scylla-cloud-backup-10-10-w836gd/scylla-manager-agent-3349653200\""}
{"L":"DEBUG","T":"2024-02-16T17:07:10.068Z","N":"rclone","M":"Waiting for deletions to finish"}
{"L":"DEBUG","T":"2024-02-16T17:07:10.173Z","N":"rclone","M":"test: Deleted"}


```
**Case #2 (VM in us-west-1; bucket in us-east-1, no explicit configuration in scylla-manager-agent.yaml)**

- configuration in `/etc/scylla-manager-agent/scylla-manager-agent.yaml ` as follow:
```
auth_token: *****
prometheus: :26090
```
(when the s3 region is not explicitly added to this config sm will use IMDS to find the EC2 instance region and apply it to config)
- `check-location` of the bucket belonging to the different region
```
scyllaadm@ip-172-31-0-200:~$ scylla-manager-agent check-location --debug --location s3:scylla-cloud-backup-9-9-2vj38h
{"L":"INFO","T":"2024-02-16T17:07:30.211Z","N":"rclone","M":"registered s3 provider [name=s3, disable_checksum=true, memory_pool_flush_time=5m, region=us-west-1, chunk_size=50M, env_auth=true, provider=AWS, upload_concurrency=2, memory_pool_use_mmap=true, no_check_bucket=true]"}
{"L":"INFO","T":"2024-02-16T17:07:30.211Z","N":"rclone","M":"registered gcs provider [name=gcs, chunk_size=50M, memory_pool_use_mmap=true, allow_create_bucket=false, memory_pool_flush_time=5m, bucket_policy_only=true]"}
{"L":"INFO","T":"2024-02-16T17:07:30.211Z","N":"rclone","M":"registered azure provider [name=azure, chunk_size=50M, disable_checksum=true, use_msi=true, memory_pool_use_mmap=true, memory_pool_flush_time=5m]"}
{"L":"DEBUG","T":"2024-02-16T17:07:30.211Z","N":"rclone","M":"Creating backend with remote \"s3:scylla-cloud-backup-9-9-2vj38h\""}
{"L":"DEBUG","T":"2024-02-16T17:07:30.211Z","N":"rclone","M":"Creating backend with remote \"/tmp/scylla-manager-agent-2349684510\""}
{"L":"INFO","T":"2024-02-16T17:07:30.272Z","N":"rclone","M":"S3 bucket scylla-cloud-backup-9-9-2vj38h: Switched region to \"us-east-1\" from \"us-west-1\""}
{"L":"DEBUG","T":"2024-02-16T17:07:30.273Z","N":"rclone","M":"pacer: low level retry 1/1 (error BucketRegionError: incorrect region, the bucket is not in 'us-west-1' region at endpoint '', bucket is in 'us-east-1' region\n\tstatus code: 301, request id: KB7VG2HKA1FCJ3BA, host id: tMn0Ywl8tbb/W2QiwycNNKOC9K0ZviVLOM443gj+ls7p7jeFjfOC99V5j5cdASvyD2U+P04tW8Q=)"}
{"L":"DEBUG","T":"2024-02-16T17:07:30.273Z","N":"rclone","M":"pacer: Rate limited, increasing sleep to 10ms"}
{"L":"DEBUG","T":"2024-02-16T17:07:30.273Z","N":"rclone","M":"S3 bucket scylla-cloud-backup-9-9-2vj38h: Waiting for checks to finish"}
{"L":"DEBUG","T":"2024-02-16T17:07:30.273Z","N":"rclone","M":"S3 bucket scylla-cloud-backup-9-9-2vj38h: Waiting for transfers to finish"}
{"L":"DEBUG","T":"2024-02-16T17:07:30.561Z","N":"rclone","M":"pacer: Reducing sleep to 0s"}
{"L":"DEBUG","T":"2024-02-16T17:07:30.833Z","N":"rclone","M":"scylla-manager-agent-2349684510/test: Copied (new)"}
{"L":"DEBUG","T":"2024-02-16T17:07:31.160Z","N":"rclone","M":"Creating backend with remote \"s3:scylla-cloud-backup-9-9-2vj38h/scylla-manager-agent-2349684510\""}
{"L":"INFO","T":"2024-02-16T17:07:31.200Z","N":"rclone","M":"S3 bucket scylla-cloud-backup-9-9-2vj38h: Switched region to \"us-east-1\" from \"us-west-1\""}
{"L":"DEBUG","T":"2024-02-16T17:07:31.200Z","N":"rclone","M":"pacer: low level retry 1/1 (error BucketRegionError: incorrect region, the bucket is not in 'us-west-1' region at endpoint '', bucket is in 'us-east-1' region\n\tstatus code: 301, request id: 21V085GS2TJVGDF0, host id: xYW0zDeeWFZCFv6L6U/pyCf/B25b4CMwMyAayb3msITTZ/q9bMg6XDUh8W10SOHe3r2OZZMthxM=)"}
{"L":"DEBUG","T":"2024-02-16T17:07:31.200Z","N":"rclone","M":"pacer: Rate limited, increasing sleep to 10ms"}
FAILED: init remote temp dir: BucketRegionError: incorrect region, the bucket is not in 'us-west-1' region at endpoint '', bucket is in 'us-east-1' region
	status code: 301, request id: 21V085GS2TJVGDF0, host id: xYW0zDeeWFZCFv6L6U/pyCf/B25b4CMwMyAayb3msITTZ/q9bMg6XDUh8W10SOHe3r2OZZMthxM=


```

@rzetelskik ^^^ looks like your case

**Case #3 (VM in us-west-1; bucket in us-east-1, explicit configuration for region in scylla-manager-agent.yaml)**

- configuration in `/etc/scylla-manager-agent/scylla-manager-agent.yaml ` as follow:
```
auth_token: *****
prometheus: :26090
s3:
  region: us-east-1
```

```
scyllaadm@ip-172-31-0-200:~$ scylla-manager-agent check-location --debug --location s3:scylla-cloud-backup-9-9-2vj38h
{"L":"INFO","T":"2024-02-16T17:08:24.365Z","N":"rclone","M":"registered s3 provider [name=s3, provider=AWS, no_check_bucket=true, region=us-east-1, memory_pool_use_mmap=true, disable_checksum=true, chunk_size=50M, memory_pool_flush_time=5m, upload_concurrency=2, env_auth=true]"}
{"L":"INFO","T":"2024-02-16T17:08:24.365Z","N":"rclone","M":"registered gcs provider [name=gcs, chunk_size=50M, memory_pool_flush_time=5m, bucket_policy_only=true, memory_pool_use_mmap=true, allow_create_bucket=false]"}
{"L":"INFO","T":"2024-02-16T17:08:24.365Z","N":"rclone","M":"registered azure provider [name=azure, memory_pool_use_mmap=true, chunk_size=50M, memory_pool_flush_time=5m, disable_checksum=true, use_msi=true]"}
{"L":"DEBUG","T":"2024-02-16T17:08:24.365Z","N":"rclone","M":"Creating backend with remote \"s3:scylla-cloud-backup-9-9-2vj38h\""}
{"L":"DEBUG","T":"2024-02-16T17:08:24.365Z","N":"rclone","M":"Creating backend with remote \"/tmp/scylla-manager-agent-3759593607\""}
{"L":"DEBUG","T":"2024-02-16T17:08:24.660Z","N":"rclone","M":"S3 bucket scylla-cloud-backup-9-9-2vj38h: Waiting for checks to finish"}
{"L":"DEBUG","T":"2024-02-16T17:08:24.660Z","N":"rclone","M":"S3 bucket scylla-cloud-backup-9-9-2vj38h: Waiting for transfers to finish"}
{"L":"DEBUG","T":"2024-02-16T17:08:25.027Z","N":"rclone","M":"scylla-manager-agent-3759593607/test: Copied (new)"}
{"L":"DEBUG","T":"2024-02-16T17:08:25.319Z","N":"rclone","M":"Creating backend with remote \"s3:scylla-cloud-backup-9-9-2vj38h/scylla-manager-agent-3759593607\""}
{"L":"DEBUG","T":"2024-02-16T17:08:25.595Z","N":"rclone","M":"Waiting for deletions to finish"}
{"L":"DEBUG","T":"2024-02-16T17:08:25.751Z","N":"rclone","M":"test: Deleted"}

```

@rzetelskik 
It totally works as expected.
If there is region defined in scylla-manager-agent.yaml explicitly, then this region will be hit trying to check-location.
If there is no region defined, SM uses IMDS to check region of current VM

I see nothing what I could change here, because it works...
Maybe calling IMDS endpoint from k8s pod causes the issue ?

I'm going to close this as cannot reproduce next week. Feel free to provide use case that actually reproduces the statement from issue description.

**Comment by rzetelskik** [comment] 2024-02-19 12:22
Thanks @karol-kokoszka. I tried it again with a region explicitly configured and I'm not getting any errors now. I must have misconfigured it before. As I can't reproduce it again, please feel free to close the issue.

**Comment by eagleusb** [comment] 2024-02-26 16:12
Hello there, I personnally encounter that problem while running Scylla Manager in AWS EKS (`us-west-2`) and trying to backup some data to S3 (`us-west-2`)

```sh
scylla@scylla-manager-79c6f8546c-t4n5s:/$ scylla-manager-agent --version
3.2.5
scylla@scylla-manager-79c6f8546c-t4n5s:/$ echo $AWS_REGION
us-west-2
scylla@scylla-manager-79c6f8546c-t4n5s:/$ echo $AWS_DEFAULT_REGION
us-west-2
```

```sh
scylla@scylla-manager-79c6f8546c-t4n5s:/$ grep -A30 '#s3:' /etc/scylla-manager-agent/scylla-manager-agent.yaml
#s3:
# S3 credentials, it's recommended to use IAM roles if possible, otherwise set
# your AWS Access Key ID and AWS Secret Access Key (password) here.
#  access_key_id:
#  secret_access_key:
#
# Provider of the S3 service. By default this is AWS. There are multiple S3
# API compatible providers that can be used instead. Due to minor differences
# between them we require that exact provider is specified here for full
# compatibility. Supported and tested options are: AWS and Minio.
# The available providers are: Alibaba, AWS, Ceph, DigitalOcean, IBMCOS, Minio,
# Wasabi, Dreamhost, Netease.
#  provider: AWS
#
# Region to connect to, if running in AWS EC2 instance region is set
# to the local region by default.
#  region:
#
# Endpoint for S3 API, only relevant when using S3 compatible API.
#  endpoint:
#
# The server-side encryption algorithm used when storing this object in S3.
# If using KMS ID you must provide the ARN of Key.
#  server_side_encryption:
#  sse_kms_key_id:
#
# The storage class to use when storing new objects in S3.
#  storage_class:
#
# Concurrency for multipart uploads.
#  upload_concurrency: 2
```

I did not explicitly defined the region but it is well defined in environment and IRSA is functional (access to s3 bucket, hence rclone calling `GetBucketLocation`)

However it does not work as expected and rclone library is throwing:

```
{"L":"ERROR","T":"2024-02-26T16:11:05.066Z","N":"rclone","M":"parse instance region: EOF","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.RedirectLogPrint.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/logger.go:19\ngithub.com/rclone/rclone/fs.LogPrintf\n\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:152\ngithub.com/rclone/rclone/fs.Errorf\n\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.awsRegionFromMetadataAPI\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/aws.go:42\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.(*S3Options).AutoFill\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/options.go:138\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.RegisterS3Provider\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/providers.go:52\nmain.setupCommand\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/setup.go:35\nmain.glob..func3\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/check_location.go:40\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.1.1/command.go:850\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.com/spf13/cobra@v1.1.1/command.go:958\ngithub.com/spf13/cobra.(*Command).Execute\n\tgithub.com/spf13/cobra@v1.1.1/command.go:895\nmain.main\n\tgithub.com/scylladb/scylla-manager/v3/pkg/cmd/agent/main.go:12\nruntime.main\n\truntime/proc.go:250"}
...

{"L":"DEBUG","T":"2024-02-26T16:11:06.380Z","N":"rclone","M":"pacer: low level retry 1/1 (error BucketRegionError: incorrect region, the bucket is not in 'us-east-1' region at endpoint '', bucket is in 'us-west-2' region\n\tstatus code: 301, request id: GQE...6B7W, host id: OMr...+UA=)"}
```

**Comment by eagleusb** [comment] 2024-02-27 10:13
And the AWS SDK v2 can be leveraged to do so https://github.com/aws/aws-sdk-go-v2/tree/v1.25.2/feature/ec2/imds

**Closed** 2024-02-28 17:07 UTC
Labels: enhancement
