### ISSUE TITLE
support fast repair on heterogeneous multi DC clusters

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-manager#3241] opened 2022-10-11 09:06 UTC
In scope of https://github.com/scylladb/scylla-enterprise/issues/2035#issuecomment-1218880844

we will need to get support for multi DC repairs that will be coordinated from DC which has lowest number of shards per node

How to reproduce?
create multi-DC cluster with 1 DC with e.g. 16 cpus per node with NVMEs(local storage) and second DC with e.g. 4 cpus per node and PDs as storage drives

get above to the manager

If you run classic repair from manager, it will take a very long time due to above GH
However if you run repair from 4 cpu nodes, it will be much much faster than above, since these nodes won't be overloaded by number of readers per shard when the repair is triggered from bigger nodes DC

Scylla Manager should support restricting coordinator nodes only to certain DC to get a fix for this issue

**Comment by vladzcloudius** [comment] 2022-10-21 21:36
No, @tarzanek , we need repairs for heterogeneous cluster to be fast regardless what node is a repair master.

I believe this issue should be closed since the problem is not in the Manager and it can not be resolved in the Manager in a general case.

**Closed** 2022-11-15 15:14 UTC
