### ISSUE TITLE
[scylla-manager-agent]: download possibly leaks file descriptors

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-manager#3190] opened 2022-07-01 22:12 UTC
Version: 2.6.3

*Descritption*
When we ran a `restore.yaml` playbook against the 16 vCPU Scylla nodes the upload command below was starting erroring out with "too many file descriptors" very soon after the beginning (less than a minute):

```
$ scylla-manager-agent download-files -L {{ backup_location }} -n {{ host_id[inventory_hostname] }} -T {{ snapshot_tag }} -d /var/lib/scylla/data/ --mode upload
```

The errors are like this:

```
fatal: [10.77.104.25]: FAILED! => {"ansible_job_id": "833585547634.12870", "changed": true, "cmd": "scylla-manager-agent download-files -L azure:scyllabackups -n a888035c-b94a-4fae-b606-3f9911e41b11 -T sm_20220626060706UTC
 -d /var/lib/scylla/data/ --mode upload\n", "delta": "0:31:33.847332", "end": "2022-07-01 18:05:49.329793", "finished": 1, "msg": "non-zero return code", "rc": 1, "start": "2022-07-01 17:34:15.482461", "stderr": "{\"L\":\"ERROR\",\
"T\":\"2022-07-01T17:34:15.547Z\",\"N\":\"rclone\",\"M\":\"parse instance region: invalid character '<' looking for beginning of value\",\"S\":\"github.com/scylladb/go-log.Logger.log\\n\\tgithub.com/scylladb/go-log@v0.0.6/logger.go
:101\\ngithub.com/scylladb/go-log.Logger.Error\\n\\tgithub.com/scylladb/go-log@v0.0.6/logger.go:84\\ngithub.com/scylladb/scylla-manager/pkg/rclone.RedirectLogPrint.func1\\n\\tgithub.com/scylladb/scylla-manager/pkg/rclone/logger.go:
19\\ngithub.com/rclone/rclone/fs.LogPrintf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:152\\ngithub.com/rclone/rclone/fs.Errorf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\\ngithub.com/scylladb/scylla-manager/pkg/rclone
.awsRegionFromMetadataAPI\\n\\tgithub.com/scylladb/scylla-manager/pkg/rclone/aws.go:42\\ngithub.com/scylladb/scylla-manager/pkg/rclone.(*S3Options).AutoFill\\n\\tgithub.com/scylladb/scylla-manager/pkg/rclone/options.go:133\\ngithub
.com/scylladb/scylla-manager/pkg/rclone.RegisterS3Provider\\n\\tgithub.com/scylladb/scylla-manager/pkg/rclone/providers.go:52\\nmain.setupCommand\\n\\tgithub.com/scylladb/scylla-manager/pkg/cmd/agent/setup.go:35\\nmain.glob..func5\
\n\\tgithub.com/scylladb/scylla-manager/pkg/cmd/agent/download_files.go:71\\ngithub.com/spf13/cobra.(*Command).execute\\n\\tgithub.com/spf13/cobra@v1.1.1/command.go:850\\ngithub.com/spf13/cobra.(*Command).ExecuteC\\n\\tgithub.com/s
pf13/cobra@v1.1.1/command.go:958\\ngithub.com/spf13/cobra.(*Command).Execute\\n\\tgithub.com/spf13/cobra@v1.1.1/command.go:895\\nmain.main\\n\\tgithub.com/scylladb/scylla-manager/pkg/cmd/agent/main.go:12\\nruntime.main\\n\\truntime
/proc.go:225\"}\n{\"L\":\"ERROR\",\"T\":\"2022-07-01T17:35:02.030Z\",\"N\":\"rclone\",\"M\":\"backup/sst/cluster/59a7c070-e856-47d7-bf99-f0da372f4a4b/dc/USWEST2/node/a888035c-b94a-4fae-b606-3f9911e41b11/keyspace/prod1_integrationla
yer/table/samson_csmapp1/289c5f60b7d011ecb4bb00000000000d/md-25232-big-Data.db: Failed to copy: multipart copy: failed to open destination: open /var/lib/scylla/data/prod1_integrationlayer/samson_csmapp1-289c5f60b7d011ecb4bb0000000
0000d/upload/md-25232-big-Data.db: too many open files\",\"S\":\"github.com/scylladb/go-log.Logger.log\\n\\tgithub.com/scylladb/go-log@v0.0.6/logger.go:101\\ngithub.com/scylladb/go-log.Logger.Error\\n\\tgithub.com/scylladb/go-log@v
0.0.6/logger.go:84\\ngithub.com/scylladb/scylla-manager/pkg/rclone.RedirectLogPrint.func1\\n\\tgithub.com/scylladb/scylla-manager/pkg/rclone/logger.go:19\\ngithub.com/rclone/rclone/fs.LogPrintf\\n\\tgithub.com/rclone/rclone@v1.51.0
/fs/log.go:152\\ngithub.com/rclone/rclone/fs.Errorf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\\ngithub.com/rclone/rclone/fs/operations.Copy\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/operations/operations.go:496\\ngithub.co
m/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/sync/sync.go:402\"}\n{\"L\":\"ERROR\",\"T\":\"2022-07-01T17:35:11.252Z\",\"N\":\"rclone\",\"M\":\"backup/sst/cluster/59a7c070-e856-47d7
-bf99-f0da372f4a4b/dc/USWEST2/node/a888035c-b94a-4fae-b606-3f9911e41b11/keyspace/prod1_integrationlayer/table/samson_csmapp18/5f17e5a0cfb311ec8a00000000000000/md-2317-big-Data.db: Failed to copy: multipart copy: failed to open dest
ination: open /var/lib/scylla/data/prod1_integrationlayer/samson_csmapp18-5f17e5a0cfb311ec8a00000000000000/upload/md-2317-big-Data.db: too many open files\",\"S\":\"github.com/scylladb/go-log.Logger.log\\n\\tgithub.com/scylladb/go-
log@v0.0.6/logger.go:101\\ngithub.com/scylladb/go-log.Logger.Error\\n\\tgithub.com/scylladb/go-log@v0.0.6/logger.go:84\\ngithub.com/scylladb/scylla-manager/pkg/rclone.RedirectLogPrint.func1\\n\\tgithub.com/scylladb/scylla-manager/p
kg/rclone/logger.go:19\\ngithub.com/rclone/rclone/fs.LogPrintf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:152\\ngithub.com/rclone/rclone/fs.Errorf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\\ngithub.com/rclone/rclone/
fs/operations.Copy\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/operations/operations.go:496\\ngithub.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/sync/sync.go:402\"}\n{\"L\":\"ERROR
\",\"T\":\"2022-07-01T17:35:11.253Z\",\"N\":\"rclone\",\"M\":\"backup/sst/cluster/59a7c070-e856-47d7-bf99-f0da372f4a4b/dc/USWEST2/node/a888035c-b94a-4fae-b606-3f9911e41b11/keyspace/prod1_integrationlayer/table/samson_csmapp18/5f17e
5a0cfb311ec8a00000000000000/md-23481-big-Data.db: Failed to copy: multipart copy: failed to open destination: open /var/lib/scylla/data/prod1_integrationlayer/samson_csmapp18-5f17e5a0cfb311ec8a00000000000000/upload/md-23481-big-Dat
a.db: too many open files\",\"S\":\"github.com/scylladb/go-log.Logger.log\\n\\tgithub.com/scylladb/go-log@v0.0.6/logger.go:101\\ngithub.com/scylladb/go-log.Logger.Error\\n\\tgithub.com/scylladb/go-log@v0.0.6/logger.go:84\\ngithub.c
om/scylladb/scylla-manager/pkg/rclone.RedirectLogPrint.func1\\n\\tgithub.com/scylladb/scylla-manager/pkg/rclone/logger.go:19\\ngithub.com/rclone/rclone/fs.LogPrintf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:152\\ngithub.com/r
clone/rclone/fs.Errorf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\\ngithub.com/rclone/rclone/fs/operations.Copy\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/operations/operations.go:496\\ngithub.com/rclone/rclone/fs/sync.(*syn
cCopyMove).pairCopyOrMove\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/sync/sync.go:402\"}\n{\"L\":\"ERROR\",\"T\":\"2022-07-01T17:35:35.873Z\",\"N\":\"rclone\",\"M\":\"backup/sst/cluster/59a7c070-e856-47d7-bf99-f0da372f4a4b/dc/USWEST2
/node/a888035c-b94a-4fae-b606-3f9911e41b11/keyspace/prod1_integrationlayer/table/samson_csmapp11_relation/6445e2c0cfb311ec905b000000000008/md-2271-big-Index.db: Failed to copy: multipart copy: failed to open destination: open /var/
lib/scylla/data/prod1_integrationlayer/samson_csmapp11_relation-6445e2c0cfb311ec905b000000000008/upload/md-2271-big-Index.db: too many open files\",\"S\":\"github.com/scylladb/go-log.Logger.log\\n\\tgithub.com/scylladb/go-log@v0.0.
6/logger.go:101\\ngithub.com/scylladb/go-log.Logger.Error\\n\\tgithub.com/scylladb/go-log@v0.0.6/logger.go:84\\ngithub.com/scylladb/scylla-manager/pkg/rclone.RedirectLogPrint.func1\\n\\tgithub.com/scylladb/scylla-manager/pkg/rclone
/logger.go:19\\ngithub.com/rclone/rclone/fs.LogPrintf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:152\\ngithub.com/rclone/rclone/fs.Errorf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\\ngithub.com/rclone/rclone/fs/operat
ions.Copy\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/operations/operations.go:496\\ngithub.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/sync/sync.go:402\"}\n{\"L\":\"ERROR\",\"T\":\"2022-07-01T17:35:45.946Z\",\"N\":\"rclone\",\"M\":\"Azure container scyllabackups: lazy init backup/sst/cluster/59a7c070-e856-47d7-bf99-f0da372f4a4b/dc/USWEST2/node/a888035c-b94a-4fae-b606-3f9911e41b11/keyspace/prod1_integrationlayer/table/samson_collapp1/1a661150c69b11eca93c00000000000b/md-2060-big-Statistics.db failed: -> github.com/Azure/azure-pipeline-go/pipeline.NewError, github.com/Azure/azure-pipeline-go@v0.2.3/pipeline/error.go:157\\nHTTP request failed\\n\\nHead \\\"https://scyllabackups.blob.core.windows.net/scyllabackups/backup/sst/cluster/59a7c070-e856-47d7-bf99-f0da372f4a4b/dc/USWEST2/node/a888035c-b94a-4fae-b606-3f9911e41b11/keyspace/prod1_integrationlayer/table/samson_collapp1/1a661150c69b11eca93c00000000000b/md-2060-big-Statistics.db?timeout=31536001\\\": dial tcp: lookup scyllabackups.blob.core.windows.net on 10.77.120.153:53: no such host\\n\",\"S\":\"github.com/scylladb/go-log.Logger.log\\n\\tgithub.com/scylladb/go-log@v0.0.6/logger.go:101\\ngithub.com/scylladb/go-log.Logger.Error\\n\\tgithub.com/scylladb/go-log@v0.0.6/logger.go:84\\ngithub.com/scylladb/scylla-manager/pkg/rclone.RedirectLogPrint.func1\\n\\tgithub.com/scylladb/scylla-manager/pkg/rclone/logger.go:19\\ngithub.com/rclone/rclone/fs.LogPrintf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:152\\ngithub.com/rclone/rclone/fs.Errorf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\\ngithub.com/rclone/rclone/fs/object.(*LazyObject).init.func1\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/object/lazy.go:37\\nsync.(*Once).doSlow\\n\\tsync/once.go:68\\nsync.(*Once).Do\\n\\tsync/once.go:59\\ngithub.com/rclone/rclone/fs/object.(*LazyObject).init\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/object/lazy.go:33\\ngithub.com/rclone/rclone/fs/object.(*LazyObject).Size\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/object/lazy.go:64\\ngithub.com/rclone/rclone/fs/sync.(*pipe).Put\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/sync/pipe.go:99\\ngithub.com/rclone/rclone/fs/sync.(*syncCopyMove).SrcOnly\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/sync/sync.go:1004\\ngithub.com/rclone/rclone/fs/march.(*March).processJob\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/march/march.go:468\\ngithub.com/rclone/rclone/fs/march.(*March).Run.func1\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/march/march.go:181\"}\n{\"L\":\"ERROR\",\"T\":\"2022-07-01T17:36:01.558Z\",\"N\":\"rclone\",\"M\":\"backup/sst/cluster/59a7c070-e856-47d7-bf99-f0da372f4a4b/dc/USWEST2/node/a888035c-b94a-4fae-b606-3f9911e41b11/keyspace/prod1_integrationlayer/table/samson_csmapp1_relation/32f09170b7d011ec989700000000000d/md-21660-big-Index.db: Failed to copy: multipart copy: failed to open destination: open /var/lib/scylla/data/prod1_integrationlayer/samson_csmapp1_relation-32f09170b7d011ec989700000000000d/upload/md-21660-big-Index.db: too many open files\",\"S\":\"github.com/scylladb/go-log.Logger.log\\n\\tgithub.com/scylladb/go-log@v0.0.6/logger.go:101\\ngithub.com/scylladb/go-log.Logger.Error\\n\\tgithub.com/scylladb/go-log@v0.0.6/logger.go:84\\ngithub.com/scylladb/scylla-manager/pkg/rclone.RedirectLogPrint.func1\\n\\tgithub.com/scylladb/scylla-manager/pkg/rclone/logger.go:19\\ngithub.com/rclone/rclone/fs.LogPrintf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:152\\ngithub.com/rclone/rclone/fs.Errorf\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\\ngithub.com/rclone/rclone/fs/operations.Copy\\n\\tgithub.com/rclone/rclone@v1.51.0/fs/operations/operations.go ...
```

We increased the `LimitNOFILES` to 80000000 and it still didn't help.
The only thing that helped was reducing the concurrency.
The default on those machines was 32.
Running the same command with `-p 1` and with `-p 6` succeeded.

**Comment by vladzcloudius** [comment] 2022-07-01 22:12
@mmatczuk FYI

**Comment by mmatczuk** [comment] 2022-07-04 08:54
I think what happens is they use the same http connection pool and the concurency causes many files being open.

**Comment by mmatczuk** [comment] 2022-07-04 08:54
To be investigated.

**Comment by slivne** [comment] 2022-07-13 08:21
So we discussed this a bit and we would like to place by default a limit that will work and if someone wants to optimize he will be able too ... need to see how todo this

**Comment by mmatczuk** [comment] 2022-07-13 12:05
I had a look in the code I see nothing particularly interesting.

We download all the tables in parallel but it's actually needed here to be able to calculate total download size and be able to show correct accounting / percent completed information.

We are not doing tons of HEAD requests since we use our custom [Lazy Object](https://github.com/scylladb/rclone/commit/78f2f807a3c46459ea2420169d225666c1e9edab). 
In theory we should be doing 10k files at once, see [MaxBacklog](https://github.com/scylladb/rclone/blob/0bf74ef6c54b72fdbe467c73aa5d874ae302d2fe/fs/sync/sync.go#L135).

This needs to be reproduced and analysed to see the source of the excessive open files.
There are two major possible culprits
- Premature opening (all destination) files on disk?
- Sending many HEAD requests beyond the configured quota resulting in opening new TCP connections

This can be reproduced using an integration test, or a manual test in dev env.
For reference we have [upload benchmark tool](https://github.com/scylladb/scylla-manager/blob/master/pkg/cmd/agent/benchmark.go).

This could be used to create many S3 objects, and we shall see what happens on download with `-p 1000`.

**Comment by karol-kokoszka** [comment] 2022-08-09 15:13
I managed to reproduce it locally using benchmark tool that @mmatczuk suggested.
Setup:
- minio in docker (s3 emulator)
- folder containing around 1000000 very small files
- scylla-manager-agent started locally with configuration containing
 ```
rclone:
  transfers: 10000
```
^^ rclone.transfer was added by me, it worked fine without it

I played with MaxBacklog as well, but seems it didn't have an impact at all for my testing.

It ends up with a lot of errors like
```
{"L":"ERROR","T":"2022-08-09T15:27:22.986+0200","N":"rclone","M":"file996: Failed to copy: failed to open source object: open /home/karkok/test/file996: too many open files","S":"github.com/scylladb/go-log.Logger.log\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:101\ngithub.com/scylladb/go-log.Logger.Error\n\tgithub.com/scylladb/go-log@v0.0.7/logger.go:84\ngithub.com/scylladb/scylla-manager/v3/pkg/rclone.RedirectLogPrint.func1\n\tgithub.com/scylladb/scylla-manager/v3/pkg/rclone/logger.go:19\ngithub.com/rclone/rclone/fs.LogPrintf\n\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:152\ngithub.com/rclone/rclone/fs.Errorf\n\tgithub.com/rclone/rclone@v1.51.0/fs/log.go:167\ngithub.com/rclone/rclone/fs/operations.Copy\n\tgithub.com/rclone/rclone@v1.51.0/fs/operations/operations.go:497\ngithub.com/rclone/rclone/fs/sync.(*syncCopyMove).pairCopyOrMove\n\tgithub.com/rclone/rclone@v1.51.0/fs/sync/sync.go:402"}
```

This cmd `➜  my-test-1 sudo timeout --signal=9 60s lsof 2>/dev/null | wc -l` gave `1345101` .

I need to understand the correlation between Transfers and MaxBacklog and will go back with proper setup.

**Comment by karol-kokoszka** [comment] 2022-08-11 10:09
Even tough I managed to reproduce the `too many open files` issue, it's not done exactly the same way that led to this error in this issue.
I actually did it by starting benchmark tool and by extending parallelism. Parameter `transfers: 1000` is basically the equivalent to `-p 1000` from the `download-files` cmd.
Default `-p` from the `download-files` is equal to the number of cores available on the machine. In this case it was set to 16. `download-files` doesn't care about `transfers: X` parameter from the scylla-manager-agent.yaml. It overrides it with the number of available cores.

`MaxBacklog` is, as per rclone documentation:
```
This is the maximum allowable backlog of files in a sync/copy/move queued for being checked or transferred.
This can be set arbitrarily large. It will only use memory when the queue is in use. Note that it will use in the order of N KiB of memory when the backlog is in use.
Setting this large allows rclone to calculate how many files are pending more accurately, give a more accurate estimated finish time and make --order-by work more accurately.
Setting this small will make rclone more synchronous to the listings of the remote which may be desirable.
Setting this to a negative number will make the backlog as large as possible.
```

I didn't manage to reproduce `too many open files` using exactly the same command as was used by the issuer.

What I tried:
- Created the cluster with 1000 tables what gave me around ~18000 files available to download from the backup location
- Added longer time.Sleep just after the file is opened by rclone to see if it will cause rclone to open much more files in the same time --> but no, rclone respected the limits it have
- I added the atomic counter to rclone on file opening and file closing to see how many files it will open during command execution --> The outcome here was that it never extended the current shell `ulimit -n`
- When I realized that it was opening at peak around 195, I reduced the limit by `ulimit -n 150` to see whether it will cause rclone to fail, but no, it didn't. Number of concurrently opened files was auto reduced to lower value. It was around 70 at peak.
- Command were executed with higher parallelism = 1000.

No effects.

But there is another thing.
@vladzcloudius mentioned that they tried to set `LimitNOFILES=80000000` on the service.
It's ok, but as per my understanding it only affects the `scylla-manager-agent` server that is running as a service on the node.
`download-files` cmd limits are independent from this values. 
Limit of max number of opened files for `download-files` is exactly the same, as the limit for the current shell session.
This limit can be checked by `ulimit -n` executed on the current shell session, and can be changed by `ulimit -n X`.

Maybe this is a case, that the limit for shell session was low.
So, the suggestion is to make it higher if needed before executing `download-files`.

@slivne as per your comment
> So we discussed this a bit and we would like to place by default a limit that will work and if someone wants to optimize he will be able too ... need to see how todo this
Do you think it's worth to mentioned that in https://manager.docs.scylladb.com/stable/restore/index.html ? I mean to check what is the current value of `ulimit -n` and to extend it if the value is low before executing the playbook ?

**Comment by vladzcloudius** [comment] 2022-08-11 18:53
> Maybe this is a case, that the limit for shell session was low.
> So, the suggestion is to make it higher if needed before executing download-files.

@karol-kokoszka 
Even if the session used to run `download-files` used a default `ulimit -n` somehow (while I still don't understand how this is possible as long as `download-files` is executed as a child process of the service in question and therefore was supposed to inherit all limits from the parent) - even then it would have 1024 descriptors to spare and I don't see how this can be not enough for a default concurrency (which according to you is 16). On top of that - which user's limits we should have been adjusting then?

Unless you have a better explanation of what we saw I don't see how increasing any limit is going to help, because if we leak descriptions - it won't.

**Comment by karol-kokoszka** [comment] 2022-08-11 22:32
@vladzcloudius 
You're most likely right.
I wrapped os.OpenFile command used by rclone into another function to sleep for a few seconds after every opening of the new file. Besides that, every 3000 file opening, I execute `lsof -p <PID>` to see how many files the process already opened.
The output with no sleep is acceptable (still higher than 16) -> around 75. (executing os cmd from go opens additional file descriptors).
But, when the sleep is set to 2s for example, then the number of files that agent opens, very quickly exceed the limit i have for my shell. I set it to 10000.

Still no "too many open files" in log. App just blocks and does nothing when the limit is reached.

Following rclone documentation
```
--transfers=N
The number of file transfers to run in parallel. It can sometimes be useful to set this to a smaller number if the remote is giving a lot of timeouts or bigger if you have lots of bandwidth and a fast remote.

The default is to run 4 file transfers in parallel.

Look at --multi-thread-streams if you would like to control single file transfers.
```
It just means that -p defines how many downloads from S3 are performed at the same time, but it doesn't limit the number of files that can be written to fs at the same time ofc.

So... still checking of what is going on under the hood of rclone.

**Comment by karol-kokoszka** [comment] 2022-10-07 09:06
My last comment is 2 months old.
Since I started investing the issue, I didn't spot anything suspicious in the code that could lead to the leaking file descriptors.
I see no sense in keeping the issue opened.

I only found couple of metrics that can be useful next time the situation occur.
These are:
- `process_open_fds` - shows how many fds are opened per job [`manager_agent`, `node_exporter`, `prometheus`, `scylla-manager`]
- `process_max_fds` - max allowed opened fds per process

Interesting spot regarding `process_max_fds` done on couple of random prod cloud clusters.
`process_max_fds{job="manager_agent"}` = **1024**  

https://github.com/scylladb/scylla-monitoring/search?q=process_open_fds&type=issues

Please reopen the issue if the problem appear again. Will check the metric values from the time it happened then.

**Comment by vladzcloudius** [comment] 2022-10-07 14:31
@karol-kokoszka I don't understand why you have decided to close this issue without any fix.

You mentioned that you WERE able to reproduce the error: https://github.com/scylladb/scylla-manager/issues/3190#issuecomment-1211785535

Then you suggested something that made little sense and later agreed that it INDEED makes little sense.

And finally after 2 months of silence you simply decided to close this?!

I'm sorry but this makes no sense to me at all. If you can't figure out what the issue is - that's ok to admit it and ask for help. 

But, please, don't close GH issues that are not fixed - they should stay opened as long as it takes.

Please, reopen this issue.

**Comment by karol-kokoszka** [comment] 2022-10-07 18:04
> It turns out that the actual concurrency of the upload is NOT defined by a -p parameter. According to Karol this parameter defines a number of workers but every worker has it's own concurrency (which one exactly, @karol-kokoszka? Please, provide a reference that confirms the actual value).

-p parameter in scylla-manager is equivalent of transfers in rclone 
See https://rclone.org/docs/ 
```
--transfers=N
The number of file transfers to run in parallel. It can sometimes be useful to set this to a smaller number if the remote is giving a lot of timeouts or bigger if you have lots of bandwidth and a fast remote.

The default is to run 4 file transfers in parallel.

Look at --multi-thread-streams if you would like to control single file transfers.
```
If -p flag is not provided then it defaults to `2*numberOfCPUs`

Scylla manager agent uses rclone to do the transfers between different storages (local and s3 for example).

So the -p is the first factor. 1 transfer suppose to be 1 file being copied.

Second one is the concurrency for downloads set in scylla manager (outside of rclone configuration). For this particular command -> `download-files`, scylla manager agent doesn't limit number of tables to be copied at the same time.
It means, that when you invoke `download-files`, scylla manager agent for every table start `-p` transfers.
It leads to the conclusion that max possible number of goroutines that suppose to open files at the same time is not = `-p`, but it's rather
`-p * number of tables`.
It's number of goroutines, not number of files being opened at the same time. There is plenty of logic around the transfer in rclone.
@vladzcloudius If you must have precise answer for the question of what is the limit for max opened files in rclone fork we support. Then yes, would be good to find some other person that can check it and confirm. I would made the statement now that it's just `number_of_tables` * `-p param`.

We don't have any flag in scylla-manager-agent to limit number of tables that are being transferred by rclone at the same time.
And frankly speaking I'm not sure if it's so important to have this parameter available on the command. Number of max open files is still quite low (assuming that there is no leak of file descriptors).

> An open question: how can process_max_fds{job="manager_agent"} get 1024?
Where exactly this is configured and why this doesn't inherit from the corresponding systemd service configuration?

I think this is crucial. 1024 is very low limit.
The point is, that I don't know what is the setup of the cluster where this problem occurred. 

@vladzcloudius 
Let's define one action point. 
I need to have an answer to the question of `What is the value of "process_max_fds{job="manager_agent"}" metric for scylla-manager-agent on the cluster where this problem appeared.`.
If it was 1024 (as on the clusters I checked), + number of tables that were being transferred was big, then it definitely can be a root cause and it defines the potential fix.

**Comment by vladzcloudius** [comment] 2022-10-07 21:18
> We don't have any flag in scylla-manager-agent to limit number of tables that are being transferred by rclone at the same time.
And frankly speaking I'm not sure if it's so important to have this parameter available on the command. Number of max open files is still quite low (assuming that there is no leak of file descriptors).

I disagree. This is *critical* to be able to control the maximum copy concurrency via some configurable. 

Let's add such a configurable.

@karol-kokoszka Let's answer the question what defines the value `process_max_fds{job="manager_agent"}` in general? 

Can you, please, answer this question?

**Comment by vladzcloudius** [comment] 2022-10-07 21:31
@slivne @DoronArazii Please, consider assigning somebody else to this issue if Karol is not willing to continue working on this.

3 months is way TOO long for such a trivial issue.

**Comment by karol-kokoszka** [comment] 2022-10-07 22:00
@vladzcloudius i've found some interesting post that describes set of default prometheus client metrics available out of the box.
https://povilasv.me/prometheus-go-metrics/
It includes explanation of 'process_max_fds' as well.
```
process_max_fds – reads /proc/{PID}/limits and uses Soft Limit from “Max Open Files” row. The interesting bit here is that /limits lists Soft and Hard limits.
As it turns out, the soft limit is the value that the kernel enforces for the corresponding resource and the Hard limit acts as a ceiling for the soft limit.
An unprivileged process may only set its soft limit to a value up to the hard limit and (irreversibly) lower its Hard limit. [5. More docs in https://linux.die.net/man/2/setrlimit]
```

My claim is that manager agent have a max limit of 1024 fds.
Having value from the cluster where the problem occured would prove me that im right or wrong with this claim.

**Comment by vladzcloudius** [comment] 2022-10-07 22:59
> @vladzcloudius i've found some interesting post that describes set of default prometheus client metrics available out of the box. https://povilasv.me/prometheus-go-metrics/ It includes explanation of 'process_max_fds' as well.
> 
> ```
> process_max_fds – reads /proc/{PID}/limits and uses Soft Limit from “Max Open Files” row. The interesting bit here is that /limits lists Soft and Hard limits.
> As it turns out, the soft limit is the value that the kernel enforces for the corresponding resource and the Hard limit acts as a ceiling for the soft limit.
> An unprivileged process may only set its soft limit to a value up to the hard limit and (irreversibly) lower its Hard limit. [5. More docs in https://linux.die.net/man/2/setrlimit]
> ```
> 
> My claim is that manager agent have a max limit of 1024 fds. Having value from the cluster where the problem occured would prove me that im right or wrong with this claim.

@karol-kokoszka You are (still) confused about what needs to be done here.
We need to understand HOW we can make sure this value is 500000 - as we intend it to be.

To your question - we checked the `/proc/{scylla-agent-pid}/limits` value on the customer's cluster and it WAS set to 500000 and later increased to `80000000`.

All this has been mentioned in the opening message.

**Comment by karol-kokoszka** [comment] 2022-10-10 13:07
@vladzcloudius 
I did couple of more check, as I wanted to prove that when you execute `scylla-manager-agent` this way
`$ scylla-manager-agent download-files -L {{ backup_location }} -n {{ host_id[inventory_hostname] }} -T {{ snapshot_tag }} -d /var/lib/scylla/data/ --mode upload`, then it doesn't derive limits for max opened files from systemd service `scylla-manager-agent`, but it just takes it from the current shell session.

I setup completely new cluster with 3 nodes and scylla-manager-agent added on each of the node.
`scylla-manager-agent` was running as a systemd service ofc.

First spot:
- default limit for max_fds is exactly **1024**, as I stated in one of my previous commits
- limit for max_fds can be changed in the service directly by
> We increased the LimitNOFILES to 80000000 and it still didn't help.

^^^ exactly this action that you wrote in issue description, done on `scylla-manager-agent` service.
I confirm that it impacts `process_max_fds` metric value I mentioned in my previous comment and `process_max_fds` metric reflects this limit change in its value.

So, the `process_max_fds` tells the truth.

Second spot:
- in this comment https://github.com/scylladb/scylla-manager/issues/3190#issuecomment-1212369549 you wrote
>  I still don't understand how this is possible as long as download-files is executed as a child process of the service in question and therefore was supposed to inherit all limits from the parent

How it was executed as a `child process of the service` ? 
From the issue description I just understand that 
`$ scylla-manager-agent download-files -L {{ backup_location }} -n {{ host_id[inventory_hostname] }} -T {{ snapshot_tag }} -d /var/lib/scylla/data/ --mode upload`
command was executed in the shell session. @vladzcloudius Please confirm if this is true.

I did a small experiment.
On the cluster that I created, I just did the following:
- SSH to the node with scylla + agent
- checked what's the value of max file descriptors in `/proc/{scylla-agent-pid}/limits` -> it was default for sm agent = 1024
- `ulimit -n 10` to extremely decrease number of max opened files for the current session
- execute command from the issue description to download-files...
- OUTPUT: 
```
STARTUP ERROR: error applying options: open /etc/scylla-manager-agent/scylla-manager-agent.yaml: too many open files
```

^^^ It's a prove that the max-fds limit was derived from current shell session, not the service itself.
Limit = 10 is so small, than agent cmd process couldn't fully start even.

Last but not least, is the problem with downloading files from the cluster that the error appeared solved by you somehow already ? Or it's still pending to download the files ?
If it's still pending, can you just do a small experiment for me and set the limit for max fd on the current shell session `ulimit -n 5000000` and then execute the command ?

Frankly speaking `scylla-manager-agent download-files` starts separated process, how it can derive limits from `scylla-manager-agent` service ?

To answer this question:
```
@karol-kokoszka You are (still) confused about what needs to be done here.
We need to understand HOW we can make sure this value is 500000 (as scylla-manager-agent has) - as we intend it to be.
```
Just change the limit for current shell session by `ulimit -n 500000`

**Comment by vladzcloudius** [comment] 2022-10-25 23:32
@karol-kokoszka 

> checked what's the value of max file descriptors in /proc/{scylla-agent-pid}/limits -> it was default for sm agent = 1024

This is an issue on its own. I double checked and, indeed, scylla-manager-agent.service doesn't set `LimitNOFILE` - I believe it should. Good catch!

Another good catch with `scylla-manager-agent download-files ...`
I indeed assumed that `scylla-manager-agent` triggers the corresponding API in the service which would create a child process. Obviously I shouldn't have assumed that.

> Last but not least, is the problem with downloading files from the cluster that the error appeared solved by you somehow already ? Or it's still pending to download the files ?

No, we have long worked the issue around and finished the cloning procedure (before I opened this GH issue) by reducing the `-p` value.

## Action items

Short term:

Since `restore.yaml` is mentioned in this page: https://manager.docs.scylladb.com/stable/restore/index.html we need to clarify there facts what have been discovered by you in this GH issue.

In particular we should probably suggest increasing NOFILES limit for a user that is going to run a playbook. What's sucks however is that this needs to be done on each Scylla node.

We should also give a sane motivation and explanation what value for NOFILES limit would make sense. Some formula that takes a number of sstables into an account.

@karol-kokoszka Please, create a corresponding GH issue towards Docs repo and suggest a new text there.

Mid/Long term: 
IMO it makes sense to actually DO make `scylla-manager-agent` trigger API of a service so that it would create a child process that would inherit limits of the service.

The service systemd configuration should have a `LimitNOFILE` value (similarly to a `scylla-server` configuration).

@mykaul FYI.

**Comment by karol-kokoszka** [comment] 2023-04-27 11:39
Addressed with documentation update made here https://github.com/scylladb/scylla-manager/pull/3300

**Closed by karol-kokoszka** 2023-04-27 11:39 UTC
Labels: high
