### ISSUE TITLE
docs: Issue in page Compatibility Matrix --> latest is SM 3.2 (missing)

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla-manager#3608] opened 2023-10-12 23:16 UTC
I would like to report an issue in page https://manager.docs.scylladb.com/branch-3.2/restore/compatibility-matrix

### Problem
latest is SM 3.2 (missing)

###  Suggest a fix
Add it please.

**Comment by Michal-Leszczynski** [comment] 2023-10-13 08:07
Duplicate of #3597

**Closed** 2023-10-13 09:48 UTC
Labels: documentation
