### ISSUE TITLE
ansible playbook doesn't work for scylla-manager-angent 3.1

### ISSUE THREAD

**Issue by d-helios** [scylladb/scylla-manager#3395] opened 2023-05-21 08:33 UTC
ansible playbook to restore backup doesn't work for scylla-manager-agent >= 3.1

**Comment by mykaul** [comment] 2023-05-21 08:36
Can you share a link for the ansible playbook? Is it part of Manager?

**Comment by mykaul** [comment] 2023-05-21 08:38
https://github.com/scylladb/scylla-manager/issues/3324 ?

**Comment by tzach** [comment] 2023-05-21 08:39
Ansible is the document way to restore backup in Manager 3.1
https://manager.docs.scylladb.com/branch-3.0/restore/index.html

Since backup process in 3.1 have not change, Ansible *should* still continue to work in the same way

**Comment by vladzcloudius** [comment] 2023-05-23 20:05
@karol-kokoszka is there any progress on that? This jeopardizes our Scylla Cloud operation. We need this to be addressed ASAP.

@mykaul, please, set/suggest a tag for this issue that would express the importance of this bug.

cc @tomer-sandler

**Comment by tomer-sandler** [comment] 2023-05-23 20:11
@karol-kokoszka  Are you 100% sure that there's no bug here and it was all due to [Siren using SM3.1.rc pkgs](https://github.com/scylladb/siren/issues/9008) and not SM3.1 final GA release ?

Was restore from backup using the ansible playbook tested properly with SM3.1? @karol-kokoszka @mykaul @roydahan

**Comment by tzach** [comment] 2023-05-24 07:57
@tomer-sandler why would you want to use Ansible with 3.1?
Is this a temp phase of the upgrade or more than that?

**Comment by tzach** [comment] 2023-05-24 08:20
https://github.com/scylladb/scylla-pkg/issues/3426

**Comment by mykaul** [comment] 2023-05-24 08:37
One lesson we have here is that we need to extend our production end-to-end tests to include the functionality - and specifically, backup-restore. I hope to see it implemented in the coming 2 weeks as part of the quality effort.

**Comment by roydahan** [comment] 2023-05-24 15:57
> @karol-kokoszka Are you 100% sure that there's no bug here and it was all due to [Siren using SM3.1.rc pkgs](https://github.com/scylladb/siren/issues/9008) and not SM3.1 final GA release ?
> 
> Was restore from backup using the "Restore from backup" Ansible playbook tested properly with SM3.1? @karol-kokoszka @mykaul @roydahan

Ansible playbook is not covered by QA and not "officially supported" by us.

**Comment by tomer-sandler** [comment] 2023-05-24 21:11
> @tomer-sandler why would you want to use Ansible with 3.1? Is this a temp phase of the upgrade or more than that?

It was @d-helios and before him @SergeiMalkov that were trying to restore a cluster for a specific customer, as part of transitioning to bigger nodes. The customer was not willing to go through the scale-up/out process (due to production impact), hence the only alternative left was restore to a new cluster with bigger nodes.

Artem can expand on what he tried, why and what worked (or did not work).

**Comment by mykaul** [comment] 2023-05-28 14:01
I think we are good now. The root cause was not identified to prevent it from happening, but the issue shouldn't happen now that we deploy 3.1 instead of 3.1rc0

**Comment by vladzcloudius** [comment] 2023-05-30 22:37
> > @karol-kokoszka Are you 100% sure that there's no bug here and it was all due to [Siren using SM3.1.rc pkgs](https://github.com/scylladb/siren/issues/9008) and not SM3.1 final GA release ?
> > Was restore from backup using the "Restore from backup" Ansible playbook tested properly with SM3.1? @karol-kokoszka @mykaul @roydahan
> 
> Ansible playbook is not covered by QA and not "officially supported" by us.

The playbook is referenced in our "SM Restore" documentation since forever, @roydahan: https://manager.docs.scylladb.com/branch-2.6/restore/index.html

I don't think it gets any more "officially supported" than this.

cc @dorlaor @mykaul

**Comment by karol-kokoszka** [comment] 2023-06-14 11:29
@tzach Following this comment https://github.com/scylladb/scylla-manager/issues/3398#issuecomment-1590750732 and answer https://github.com/scylladb/scylla-manager/issues/3398#issuecomment-1590799526
Can I close this issue ? Do we want to keep ansible script up to date with latest scylla-manager releases ? Maybe we should remove it at all from latest releases ?

**Closed** 2023-07-12 10:34 UTC
Labels: high, v3.1
