### ISSUE TITLE
Too high repair parallelism

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-manager#3463] opened 2023-07-12 03:00 UTC
Version: 3.1.1
Cluster size: 9
RF: 3
parallel: 0
max_repair_ranges_in_parallel: 6
intensity: 1

*Description*
According to SM doc pages (https://manager.docs.scylladb.com/stable/sctool/repair.html#id8) the parallelism for a KS with RF=3 and cluster with 9 nodes is supposed to be 3.

However we see that the effective parallelism is much more than that:

```
$ run scylla_hosts curl  http://127.0.0.1:10000/storage_service/active_repair
Elapsed: 00:01 - running on Scylla nodes: 'curl http://127.0.0.1:10000/storage_service/active_repair'...-
running on Scylla nodes: 'curl http://127.0.0.1:10000/storage_service/active_repair': done. Took: 1.43 seconds.
╒══════════════════════════════════════════╤═══════════════════════════════════════╤══════════════╕
│ Scylla host                              │ Result                                │ Duration     │
╞══════════════════════════════════════════╪═══════════════════════════════════════╪══════════════╡
│ scylla-xxx-xxxx-xxxx-asia-southeast1-a-1 │ []                                    │ 0.68 seconds │
├──────────────────────────────────────────┼───────────────────────────────────────┼──────────────┤
│ scylla-xxx-xxxx-xxxx-asia-southeast1-b-1 │ [5,4,3,2,1]                           │ 0.67 seconds │
├──────────────────────────────────────────┼───────────────────────────────────────┼──────────────┤
│ scylla-xxx-xxxx-xxxx-asia-southeast1-c-1 │ [14,13,12,11,10,9,8,7,6]              │ 0.67 seconds │
├──────────────────────────────────────────┼───────────────────────────────────────┼──────────────┤
│ scylla-xxx-xxxx-xxxx-asia-southeast1-a-3 │ [5,4,3,2,1]                           │ 0.68 seconds │
├──────────────────────────────────────────┼───────────────────────────────────────┼──────────────┤
│ scylla-xxx-xxxx-xxxx-asia-southeast1-b-3 │ []                                    │ 0.68 seconds │
├──────────────────────────────────────────┼───────────────────────────────────────┼──────────────┤
│ scylla-xxx-xxxx-xxxx-asia-southeast1-c-3 │ [5,4,3,2,1]                           │ 0.69 seconds │
├──────────────────────────────────────────┼───────────────────────────────────────┼──────────────┤
│ scylla-xxx-xxxx-xxxx-asia-southeast1-a-4 │ []                                    │ 0.68 seconds │
├──────────────────────────────────────────┼───────────────────────────────────────┼──────────────┤
│ scylla-xxx-xxxx-xxxx-asia-southeast1-b-4 │ [151,150,149,148,147,146,145,144,143] │ 0.68 seconds │
├──────────────────────────────────────────┼───────────────────────────────────────┼──────────────┤
│ scylla-xxx-xxxx-xxxx-asia-southeast1-c-4 │ [37,36,35,33,34]                      │ 0.67 seconds │
╘══════════════════════════════════════════╧═══════════════════════════════════════╧══════════════╛
```

As we can see there are 4*5 + 2*9 = 38 repair jobs running at the same time. 
This doesn't seem to correlate with the documentation referenced above.

**Comment by vladzcloudius** [comment] 2023-07-12 03:01
cc @raphaelsc @asias

**Comment by asias** [comment] 2023-07-12 03:18
Scylla manager is supposed to guarantee only one repair job (either repair master or follower) is running on a given host.

The results from curl http://127.0.0.1:10000/storage_service/active_repair alone showed the problem. The node b-4 is having 9 repair jobs (repair master). There must be something wrong with SM scheduling.   

```
scylla-xxx-xxxx-xxxx-asia-southeast1-b-4 │ [151,150,149,148,147,146,145,144,143]
```

**Comment by mykaul** [comment] 2023-07-12 07:01
Dup of https://github.com/scylladb/scylla-manager/issues/3362 ?

**Comment by karol-kokoszka** [comment] 2023-07-12 07:05
Yes, we know that there is a bug in repair implementation on scylla-manager side leading to the situation that more than one job is send to a single host.
The effective parallelism is mostly broken by the `--intensity` flag.

And I confirm that manager schedules much more than just a single job per host.

https://github.com/scylladb/scylla-manager/issues/3423

> The results from curl http://127.0.0.1:10000/storage_service/active_repair alone showed the problem. The node b-4 is having 9 repair jobs (repair master). There must be something wrong with SM scheduling.

There is something wrong in the SM repair implementation indeed.

Scylla-manager 3.2 is going to address issues with the repair.

**Comment by karol-kokoszka** [comment] 2023-07-12 07:08
I linked this issue to the `Update the repair procedure` epic. 
It will be solved when the epic is done.

**Comment by karol-kokoszka** [comment] 2023-07-12 20:04
> Dup of https://github.com/scylladb/scylla-manager/issues/3362 ?

No, it's not a duplicate of repairing table by table.
There is general bug in current repair implementation that leads to the situation described in this issue.
Scylla manager doesn't guarantee that one host participates in single repair job.

**Comment by vladzcloudius** [comment] 2023-07-12 21:39
> Dup of #3362 ?

Unrelated, @mykaul.
In the output above only a single table (!) being repaired.

**Comment by vladzcloudius** [comment] 2023-07-12 21:41
```
Every 2.0s: sctool --cluster sharechat-moj-post-like-service-cluster task progress repair/356c287b-88e8-4707-92ef-e19a4968d974                                            scylla-manager-moj-post-like-asia-1: Wed Jul 12 21:40:05 2023

Command "progress" is deprecated, use sctool backup|repair progress instead.

Run:            085cbf62-205e-11ee-b4e6-4201ac1300bb
Status:         RUNNING
Start time:     12 Jul 23 02:44:33 UTC
Duration:       18h55m32s
Progress:       88%
Intensity:      0.2
Parallel:       1
Datacenters:
  - asia-southeast1

╭───────────────────────────────┬────────────────────────────────┬──────────┬──────────╮
│ Keyspace                      │                          Table │ Progress │ Duration │
├───────────────────────────────┼────────────────────────────────┼──────────┼──────────┤
│ audit                         │                      audit_log │ 93%      │ 0s       │
├───────────────────────────────┼────────────────────────────────┼──────────┼──────────┤
│ post_service                  │               post_like_scylla │ 51%      │ 0s       │
│ post_service                  │            post_like_scylla_mv │ 47%      │ 37m13s   │
├───────────────────────────────┼────────────────────────────────┼──────────┼──────────┤
│ system_auth                   │                role_attributes │ 100%     │ 0s       │
│ system_auth                   │                   role_members │ 96%      │ 0s       │
│ system_auth                   │               role_permissions │ 96%      │ 0s       │
│ system_auth                   │                          roles │ 96%      │ 0s       │
├───────────────────────────────┼────────────────────────────────┼──────────┼──────────┤
│ system_distributed_everywhere │ cdc_generation_descriptions_v2 │ 0%       │ 0s       │
├───────────────────────────────┼────────────────────────────────┼──────────┼──────────┤
│ system_distributed            │    cdc_generation_descriptions │ 93%      │ 0s       │
│ system_distributed            │      cdc_generation_timestamps │ 93%      │ 0s       │
│ system_distributed            │    cdc_streams_descriptions_v2 │ 93%      │ 0s       │
│ system_distributed            │                 service_levels │ 93%      │ 0s       │
│ system_distributed            │              view_build_status │ 93%      │ 0s       │
├───────────────────────────────┼────────────────────────────────┼──────────┼──────────┤
│ system_traces                 │                         events │ 93%      │ 0s       │
│ system_traces                 │                  node_slow_log │ 89%      │ 0s       │
│ system_traces                 │         node_slow_log_time_idx │ 89%      │ 0s       │
│ system_traces                 │                       sessions │ 93%      │ 0s       │
│ system_traces                 │              sessions_time_idx │ 89%      │ 0s       │
╰───────────────────────────────┴────────────────────────────────┴──────────┴──────────╯

```

^^ is the SM repair status related to the current report .
As you can see only a `post_service.post_like_scylla_mv` is being repaired.

**Comment by vladzcloudius** [comment] 2023-07-14 14:33
@mykaul @tzach @karol-kokoszka this issue is of the highest priority for the Field.
I'm really puzzled how such a terrible bug has been known for so long and wasn't at the top of the priority list of SM team.

To remind you, SM was developed as an evolution of the aforementioned `scylla-repair` script written by @asias (some customers are still using it BTW - now I understand why) which main advantage over `nodetool repair` was the ability to control the repair parallelism (by submitting repair tasks with strategically chosen token ranges).

It wasn't a backup, not restore, not healthcheck, not 'crontab' - it was all about the repair our customers with big enough clusters were suffering. Other things came much later.

And now it turns out that **the main** feature is known to be broken for at least a month at least and it's staged for some future 3.2 only?!

It's a regression that must be fixed ASAP.

@karol-kokoszka could you, please, clarify since when this regression is in SM?

cc @dorlaor @harel-z

**Comment by vladzcloudius** [comment] 2023-07-14 14:33
cc @eliransin

**Comment by vladzcloudius** [comment] 2023-07-14 14:33
cc @ruthea

**Comment by vladzcloudius** [comment] 2023-07-14 14:40
cc @tomer-sandler @AdamStawarz @noellymedina

**Comment by karol-kokoszka** [comment] 2023-07-14 14:59
@vladzcloudius this issue is not a regression. At least for managers > 3.0.0.
Hard to tell when it was introduced exactly. 
According to the history of changes made on repair service https://github.com/scylladb/scylla-manager/commits/master/pkg/service/repair the latest changes that are touching the core of repair comes from the end of 2021.
It could be introduced around 2.4 release of the manager.

It's part of 3.2 because we want to completely revisit the repair and not just fire fight. We confirmed with our tests before, that this what our documentation says (https://manager.docs.scylladb.com/stable/sctool/repair.html#parallel)

> --parallel
The maximum number of Scylla repair jobs that can run at the same time (on different token ranges and replicas). Each node can take part in at most one repair at any given moment.

.. is not true.

SM doesn't guarantee that each node can take part in at most one repair job at any given moment.

**Comment by vladzcloudius** [comment] 2023-07-14 15:04
> @vladzcloudius this issue is not a regression. 

I'm pretty sure it is.

> At least for managers > 3.0.0. Hard to tell when it was introduced exactly. According to the history of changes made on repair service https://github.com/scylladb/scylla-manager/commits/master/pkg/service/repair the latest changes that are touching the core of repair comes from the end of 2021. It could be introduced around 2.4 release of the manager.

Let's make an effort and find when the regression was introduced exactly.

> 
> It's part of 3.2 because we want to completely revisit the repair and not just fire fight. We confirmed with our tests before, that this what our documentation says (https://manager.docs.scylladb.com/stable/sctool/repair.html#parallel)
> 
> > --parallel
> > The maximum number of Scylla repair jobs that can run at the same time (on different token ranges and replicas). Each node can take part in at most one repair at any given moment.
> 
> .. is not true.
> 
> SM doesn't guarantee that each node can take part in at most one repair job at any given moment.

We need to make sure it is and we need to make sure it is ASAP.
The exposure is 100% of our customers.
The impact is a degraded performance at least.
And an inability to run repairs due to other bugs we have that are being triggered by a too high repair concurrency.

The absurd is that SM creates a repair concurrency higher than `nodetool repair` which was supposed to be exactly the opposite.

**Comment by vladzcloudius** [comment] 2023-07-14 15:06
@BorishuV Why this task was moved to "Eliran's team" project while SM and the corresponding team are in @gmizrahi organization?

**Comment by karol-kokoszka** [comment] 2023-07-14 15:35
> Let's make an effort and find when the regression was introduced exactly.

What's a benefit of knowing since when the parallelism is broken. My first shot is that it could be introduced together with the support for <0, 1> float values for intensity flag.

We know that the repair effective parallelism is broken, I'm just surprised that this bug is found so late.
Looks that we didn't check the parallelism with neither sm integration tests nor QA tests.

Whenever 3.2 is released, we should inform customers to upgrade their version.

**Comment by vladzcloudius** [comment] 2023-07-14 15:42
> > Let's make an effort and find when the regression was introduced exactly.
> 
> What's a benefit of knowing since when the parallelism is broken. 

Too many to even discuss it to be honest.
Here are a few:
1) Once you find when the regression was introduced you would find what broke it and we will then decide what's the best way to fix it.
2) Almost all our customers are using SM and we need to know who's exposed (according to the SM they are using at the moment).

@mykaul could you, please, help with prioritizing the "find when the regression was introduced" task at @karol-kokoszka tasks list?

@karol-kokoszka, please, keep us posted about what you have found.
Thanks.

> My first shot is that it could be introduced together with the support for <0, 1> float values for intensity flag.
> 
> We know that the repair effective parallelism is broken, I'm just surprised that this bug is found so late. Looks that we didn't check the parallelism with neither sm integration tests nor QA tests.
> 
> Whenever 3.2 is released, we should inform customers to upgrade their version.

**Comment by karol-kokoszka** [comment] 2023-07-14 15:47
We define the best way to fix repair in this document https://docs.google.com/document/d/1mBaufbomXU6hDO_25KkhC7CO65AbFgKpHVpB5Mei8xA/edit#heading=h.o646d4880ftd

**Comment by vladzcloudius** [comment] 2023-07-14 15:48
> We define the best way to fix repair in this document https://docs.google.com/document/d/1mBaufbomXU6hDO_25KkhC7CO65AbFgKpHVpB5Mei8xA/edit#heading=h.o646d4880ftd

Without know what broke it and when it's all irrelevant.
@karol-kokoszka, please, tell us since when the SM was broken.
Thank you.

**Comment by vladzcloudius** [comment] 2023-07-14 19:12
Any updates on finding the regression point, @karol-kokoszka?

cc @gmizrahi @ruthea @mykaul

**Comment by karol-kokoszka** [comment] 2023-07-14 19:57
@vladzcloudius Why do you expect me to sit now and find the exact commit from the past that is the root-cause for this issue ???
I'm not gonna do that now.

We realized that there is an issue in the overall repair procedure when started working on https://github.com/scylladb/scylla-manager/issues/3362
During code analysis + playing with the integration tests we have + changing the default configuration for these integration-tests + reading the official scylla manager documentation + confirming expected state with Scylla Core, that the implementation doesn't match the documentation and it even doesn't match the blog posts we have about the repair in scylla manager.

One of the finding was that the number of jobs send to single host is much higher than 1.
The solution we want to apply is described in the google doc I put to one of the comments.
Do you want to change this approach ? Then github comments is not the best way for achieving that.

If knowing the exact point in time is the must, I can do it, but I need to hear a good explanation of why it is so important.

**Comment by vladzcloudius** [comment] 2023-07-17 13:41
putting a "regression" label because early versions of SM (based on my personal regression testing - apparently before 2.5) definitely kept the repair parallelism as our documentation states. 
It was the main reason why SM came to existence - keep repair parallelism and thus its "intensity" controlled.

**Closed** 2023-08-14 09:58 UTC
Labels: bug, repair, high, v3.2, regression
