### ISSUE TITLE
Tablets support

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylla-manager#3636] opened 2023-11-13 15:01 UTC
This is a tracker / meta-issue to ensure Manager is compatible with Tablets (OSS 6.0 / following Enterprise release)

**Comment by tzach** [comment] 2023-11-20 09:56
In particualr, tablet repair API will not include range by range repair.
@tgrabiec @asias do we have the API for tabelt repair?

https://github.com/scylladb/scylladb/issues/16101

**Comment by bhalevy** [comment] 2023-12-22 15:26
@mykaul do we need to keep both this issue and #3516?
Maybe close this one as duplicate

**Comment by avikivity** [comment] 2023-12-24 16:10
Closing as duplicate of https://github.com/scylladb/scylla-manager/issues/3516#issuecomment-1867816102

**Closed by avikivity** 2023-12-24 16:10 UTC
