### ISSUE TITLE
crash for a supported configuration

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla-manager#3260] opened 2022-11-07 13:20 UTC
Hello
scylla manager version 3.0.1-0.20220908.22faa98a263 crashes on me with:

```
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]:         github.com/scylladb/scylla-manager/v3/pkg/util/parallel/parallel.go:54 +0xce
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: created by github.com/scylladb/scylla-manager/v3/pkg/util/parallel.Run
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]:         github.com/scylladb/scylla-manager/v3/pkg/util/parallel/parallel.go:69 +0x9f
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: github.com/scylladb/scylla-manager/v3/pkg/util/parallel.Run.func1()
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]:         github.com/scylladb/scylla-manager/v3/pkg/service/healthcheck/runner.go:99 +0x336
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: github.com/scylladb/scylla-manager/v3/pkg/service/healthcheck.runner.checkHosts.func1(0x5)
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]:         github.com/scylladb/scylla-manager/v3/pkg/service/healthcheck/service.go:380 +0x293
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: github.com/scylladb/scylla-manager/v3/pkg/service/healthcheck.(*Service).pingCQL(0x11da19d?, {0x2b664c8, 0xc0004742d0}, {{0>
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]:         github.com/scylladb/scylla-manager/v3/pkg/ping/cqlping/cqlping.go:38 +0xa5
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: github.com/scylladb/scylla-manager/v3/pkg/ping/cqlping.Ping({0x2b664c8?, 0xc0004742d0?}, {{0xc000512ad0, 0xc}, {0xc000512c2>
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]:         github.com/scylladb/scylla-manager/v3/pkg/ping/cqlping/cqlping.go:158 +0x459
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: github.com/scylladb/scylla-manager/v3/pkg/ping/cqlping.queryPing({0x2b664c8?, 0xc0004742d0?}, {{0xc000512ad0, 0xc}, {0xc000>
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]:         github.com/gocql/gocql@v0.0.0-20200131111108-92af2e088537/exec.go:81 +0x37d
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: github.com/gocql/gocql.NewSingleHostQueryExecutor(0x1574a40?)
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]:         github.com/gocql/gocql@v0.0.0-20200131111108-92af2e088537/control.go:181 +0x193
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: github.com/gocql/gocql.(*controlConn).shuffleDial(0xc000207cc0?, {0xc000548258?, 0x1?, 0x169bd27?})
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]:         github.com/gocql/gocql@v0.0.0-20200131111108-92af2e088537/conn.go:209
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: github.com/gocql/gocql.(*Session).dial(...)
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]:         github.com/gocql/gocql@v0.0.0-20200131111108-92af2e088537/conn.go:219 +0x136
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: github.com/gocql/gocql.(*Session).dialWithDialer(0xc0007a3180, {0x2b66420?, 0xc000207c40?}, 0x464e9a?, 0xc000404c00?, {0x2b>
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]:         github.com/gocql/gocql@v0.0.0-20200131111108-92af2e088537/conn.go:234 +0x85
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: github.com/gocql/gocql.(*Session).dialWithoutObserver(0xc0007a3180, {0x2b66420, 0xc000207c40}, 0xc00085ab60, 0xc000557d40, >
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]:         github.com/gocql/gocql@v0.0.0-20200131111108-92af2e088537/host_source.go:188 +0x174
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: github.com/gocql/gocql.(*HostInfo).ConnectAddress(0xc00085ab60)
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: goroutine 334 [running]:
Nov 07 13:02:47 gcp-scylla-cloud-management-a scylla-manager[2226242]: panic: no valid connect address for host: [HostInfo hostname="0.0.0.0" connectAddress="0.0.0.0" peer="<nil>" rpc_address="<> broadcast_address="<nil>" preferred_ip="<nil>" connect_addr="0.0.0.0"  connect_addr_source="invalid" port=9042 data_centre="" rack="" host_id="" version="v0.0.0" state=UP num_tokens=0]. Is your cluster configured correctly?
```

So my cluster config in scylla nodes scylla.yaml has:
```
rpc_address: 0.0.0.0
broadcast_rpc_address: 0.0.0.0
```
but listen_address, broadcast_address are set to actual IPv4 address
and api_address is 127.0.0.1

also how to cleanup above? since scylla-manager is not even starting now ...

**Comment by tarzanek** [comment] 2022-11-07 13:34
flow of actions was add a new scylla cluster (with nodes that have above network config)
check sctool status, which eventually started erroring out
```
$ sctool status
Error: Get "http://127.0.0.1:5080/api/v1/clusters": dial tcp 127.0.0.1:5080: connect: connection refused
```
and then of course the server couldn't be started anymore

**Comment by tarzanek** [comment] 2022-11-07 14:33
after deleting the credentials for the cluster server started up:
```
delete from scylla_manager.secrets where cluster_id=f31611ec-791b-41d2-ae5e-ed4c31bc9b9d;
```

**Comment by karol-kokoszka** [comment] 2022-11-08 15:39
@tarzanek I managed to reproduce it locally by simply setting 
```
rpc_address: 0.0.0.0
broadcast_rpc_address: 0.0.0.0
```
Please note, that this is not the correct and supported configuration.
Following scylla.yaml from scylladb repo
https://github.com/scylladb/scylladb/blob/243fcb96f042dea0742f24097f85e1c77621973a/conf/scylla.yaml#L197-L198

```
# Note that unlike listen_address, you can specify 0.0.0.0, but you must also
# set broadcast_rpc_address to a value other than 0.0.0.0.
#
# For security reasons, you should not expose this port to the internet.  Firewall it if needed.
#
# If you choose to specify the interface by name and the interface has an ipv4 and an ipv6 address
# you can specify which should be chosen using rpc_interface_prefer_ipv6. If false the first ipv4
# address will be used. If true the first ipv6 address will be used. Defaults to false preferring
# ipv4. If there is only one address it will be selected regardless of ipv4/ipv6.
rpc_address: localhost
```

About `broadcast_rpc_address`
https://github.com/scylladb/scylladb/blob/243fcb96f042dea0742f24097f85e1c77621973a/conf/scylla.yaml#L257-L261
```
# RPC address to broadcast to drivers and other Scylla nodes. This cannot
# be set to 0.0.0.0. If left blank, this will be set to the value of
# rpc_address. If rpc_address is set to 0.0.0.0, broadcast_rpc_address must
# be set.
# broadcast_rpc_address: 1.2.3.4
```

This is not a bug in scylla-manager.
Please correct the nodes configuration.

I'm closing this issue.

**Closed by karol-kokoszka** 2022-11-08 15:39 UTC

**Comment by tarzanek** [comment] 2022-11-09 18:01
hmm, Scylla Cloud uses one of these values as 0.0.0.0 too ... let me check

**Comment by tarzanek** [comment] 2022-11-10 09:25
ok, I see the problem now
we wrongly set the broadcast_rpc_address in our code!
thanks for pointing that out
