### ISSUE TITLE
failed repairs on dev clusters

### ISSUE THREAD

**Issue by SergeiMalkov** [scylladb/scylla-manager#3251] opened 2022-11-01 12:48 UTC
# Installations details

```yaml
Scylla Cloud, production environment
Affected Clusters: 4252, 4253, 6467, 7269
Scylla Manager versions:
  Clusters 4252, 6467, 726:
    Client version: 2.6.3-0.20220307.89b222a1a68
    Server version: 2.6.3-0.20220307.89b222a1a68
  
  Cluster 4253:
    Client version: 3.0.0-0.20220523.5501e5d7f53
    Server version: 3.0.0-0.20220523.5501e5d7f53
```

# Abstract

Repairs fail with the following error: "optimize small tables: fetch table disk size report: shard count: giving up after 3 attempts: agent [HTTP 502] cannot read response: unexpected end of JSON input".
I can't understand where does this error come from and error messages and logs entries aren't of a great help for me. The following issue is divided into two chapters for corresponding version of Scylla Manager version.
I need to upgrade customer's clusters from 2.6.3 to 3.0.0, but the upgrade itself doesn't address the issue.

**Comment by SergeiMalkov** [comment] 2022-11-01 12:50
@karol-kokoszka , this issue  interferes with Scylla Manager upgrades from 2.6.3. to 3.0.0.
 I could leave the installations intact so you can investigate both 2.6.3 and 3.0.0 versions or migrate managers to 3.0.0 and that will leave us with one version to consider. Please let me know which approach seems more reasonable.

**Comment by karol-kokoszka** [comment] 2022-11-01 13:17
@SergeiMalkov see https://github.com/scylladb/scylla-manager/issues/3235
Issue is addresed already, but manager containing it is not released yet. There is a workaround for it that requires setting prometheus address in scylla. See https://github.com/scylladb/scylla-enterprise/issues/2405#issue-1376346558

**Comment by SergeiMalkov** [comment] 2022-11-01 13:33
Well, I suppose that the least problematic solution will be to wait for release `3.0.1`, which might be released pretty soon. It would be easier to wait for the most recent release instead of agreeing on running rolling restart on 4 hulu production clusters.

**Comment by karol-kokoszka** [comment] 2022-11-01 13:45
Duplicate of https://github.com/scylladb/scylla-manager/issues/3235

**Closed by karol-kokoszka** 2022-11-01 13:45 UTC
