### ISSUE TITLE
Don't assume that SM has CQL access to all of the nodes

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylla-manager#3984] opened 2024-08-20 09:13 UTC
There might be setups in which different DCs use different certs and SM can connect via CQL to only one of them.
This means that we can't assume that if SM has CQL creds, then it can connect to any host via CQL.
An example of this assumption can be seen when SM creates a single host CQL session when dumping the schema:
```go
StageAwaitSchema: func() error {
			descSchemaHost := liveNodes[0].Addr
			session, err := s.clusterSession(ctx, clusterID, cluster.SingleHostSessionConfigOption(descSchemaHost))
```

**Comment by karol-kokoszka** [comment] 2024-09-23 09:32
Duplicate of https://github.com/scylladb/scylla-manager/issues/4007

**Closed by karol-kokoszka** 2024-09-23 09:32 UTC
