### ISSUE TITLE
Ensure only single repair job per host is executed during the repair (backport to < 3.2)

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla-manager#3480] opened 2023-07-17 11:01 UTC
We must ensure that this what is written in scylla-manager docs
https://manager.docs.scylladb.com/stable/sctool/repair.html#parallel
is met by the implementation.

> The maximum number of Scylla repair jobs that can run at the same time (on different token ranges and replicas). **Each node can take part in at most one repair at any given moment**. By default the maximum possible parallelism is used. The effective parallelism depends on a keyspace replication factor (RF) and the number of nodes. The formula to calculate is is as follows: number of nodes / RF, ex. for 6 node cluster with RF=3 the maximum parallelism is 2

**Each node can take part in at most one repair at any given moment** is not met for now -> see https://github.com/scylladb/scylla-manager/issues/3463#issuecomment-1631789229

3.2 release is going to update the overall repair in scylla-manager, but we must support previous versions as well.
As the repair in 3.2 is kind of bigger refactor, this issue is supposed to guarantee the max number of repair jobs execution on single host for SM < 3.2 and the fix must be backported to all supported SM versions.

+ Add integration test veryfing the number of jobs being executed at the moment.

**Comment by karol-kokoszka** [comment] 2023-07-17 11:19
The change cannot be merged to master, but to branch-3.0, branch-3.1, branch-2.6.

**Comment by vladzcloudius** [comment] 2023-07-17 16:34
> 3.2 release is going to update the overall repair in scylla-manager, but we must support previous versions as well.

@karol-kokoszka @mykaul 
If what Karol is referring are https://github.com/scylladb/scylla-manager/issues/3425 and https://github.com/scylladb/scylla-manager/issues/3424 then, please, reconsider.

Please, see my comments there.
I believe there is no reason to change the current semantics of either `intensity` and `parallel` repair parameters. 
All we need to do is make sure they are working as advertised.

**Comment by vladzcloudius** [comment] 2023-07-18 19:38
Isn't this a duplicate of https://github.com/scylladb/scylla-manager/issues/3463 ?

**Comment by mykaul** [comment] 2023-08-20 10:37
I think this should be closed.

**Closed** 2023-08-27 14:02 UTC
Labels: bug, repair, high, Needs Backport - 3.1
