### ISSUE TITLE
'sctool status' gets stuck when repair and backup are running at the same time

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla-manager#3519] opened 2023-08-09 20:00 UTC
HEAD: 9b3527fc538381216ec7076a033f8d7363e91c6d

*Description*

Where is a `repair` and a `backup` tasks running at the same time and one runs `sctool status` it gets stuck.

**Comment by Michal-Leszczynski** [comment] 2023-08-25 11:40
Sorry for a late response. I couldn't reproduce this issue locally by simply running two tasks at once:
```
[miles@fedora scylla-manager]$ ./sctool start -c myc repair
[miles@fedora scylla-manager]$ ./sctool start -c myc backup
[miles@fedora scylla-manager]$ ./sctool status -c myc
Datacenter: dc1
╭────┬────────────┬──────────┬──────────┬────────────────┬──────────┬──────┬─────────┬────────┬──────────┬──────────────────────────────────────╮
│    │ Alternator │ CQL      │ REST     │ Address        │ Uptime   │ CPUs │ Memory  │ Scylla │ Agent    │ Host ID                              │
├────┼────────────┼──────────┼──────────┼────────────────┼──────────┼──────┼─────────┼────────┼──────────┼──────────────────────────────────────┤
│ UN │ UP (1ms)   │ UP (5ms) │ UP (0ms) │ 192.168.200.11 │ 3h13m42s │ 16   │ 31.063G │ 5.1.13 │ Snapshot │ 170df8df-dbdb-4967-a10e-b7f53df30fdd │
│ UN │ UP (3ms)   │ UP (5ms) │ UP (0ms) │ 192.168.200.12 │ 3h13m42s │ 16   │ 31.063G │ 5.1.13 │ Snapshot │ d3bf458d-94b8-4bfc-847f-22bce4d56edb │
│ UN │ UP (4ms)   │ UP (5ms) │ UP (0ms) │ 192.168.200.13 │ 3h13m42s │ 16   │ 31.063G │ 5.1.13 │ Snapshot │ fefd4a4a-e3a0-48a0-a0b2-7776635c6488 │
╰────┴────────────┴──────────┴──────────┴────────────────┴──────────┴──────┴─────────┴────────┴──────────┴──────────────────────────────────────╯
Datacenter: dc2
╭────┬────────────┬──────────┬──────────┬────────────────┬──────────┬──────┬─────────┬────────┬──────────┬──────────────────────────────────────╮
│    │ Alternator │ CQL      │ REST     │ Address        │ Uptime   │ CPUs │ Memory  │ Scylla │ Agent    │ Host ID                              │
├────┼────────────┼──────────┼──────────┼────────────────┼──────────┼──────┼─────────┼────────┼──────────┼──────────────────────────────────────┤
│ UN │ UP (1ms)   │ UP (5ms) │ UP (0ms) │ 192.168.200.21 │ 3h13m42s │ 16   │ 31.063G │ 5.1.13 │ Snapshot │ 60743e34-7bb9-417e-b697-5bcfc3529f21 │
│ UN │ UP (3ms)   │ UP (5ms) │ UP (0ms) │ 192.168.200.22 │ 3h13m42s │ 16   │ 31.063G │ 5.1.13 │ Snapshot │ 3579f7cc-eb17-4a12-b643-caefd77a85a2 │
│ UN │ UP (1ms)   │ UP (5ms) │ UP (0ms) │ 192.168.200.23 │ 3h13m42s │ 16   │ 31.063G │ 5.1.13 │ Snapshot │ 68d0a9c7-655e-4c7a-ade0-eb753f17549c │
╰────┴────────────┴──────────┴──────────┴────────────────┴──────────┴──────┴─────────┴────────┴──────────┴──────────────────────────────────────╯
[miles@fedora scylla-manager]$ ./sctool tasks -c myc
╭─────────────────────────────────────────────┬─────────────┬────────┬───────────────┬─────────┬───────┬─────────────────────────┬────────────┬─────────┬─────────────────────────╮
│ Task                                        │ Schedule    │ Window │ Timezone      │ Success │ Error │ Last Success            │ Last Error │ Status  │ Next                    │
├─────────────────────────────────────────────┼─────────────┼────────┼───────────────┼─────────┼───────┼─────────────────────────┼────────────┼─────────┼─────────────────────────┤
│ backup/4fa6c3ec-231e-49d1-b54f-606e9b75801a │             │        │ Europe/Warsaw │ 1       │ 0     │ 25 Aug 23 13:17:34 CEST │            │ RUNNING │                         │
│ healthcheck/alternator                      │ @every 15s  │        │ Europe/Warsaw │ 34      │ 0     │ 25 Aug 23 13:25:19 CEST │            │ DONE    │ 25 Aug 23 13:25:34 CEST │
│ healthcheck/rest                            │ @every 1m0s │        │ Europe/Warsaw │ 8       │ 0     │ 25 Aug 23 13:25:04 CEST │            │ DONE    │ 25 Aug 23 13:26:04 CEST │
│ healthcheck/cql                             │ @every 15s  │        │ Europe/Warsaw │ 34      │ 0     │ 25 Aug 23 13:25:19 CEST │            │ DONE    │ 25 Aug 23 13:25:34 CEST │
│ repair/bd6b45f5-ab44-4ebf-901b-af95deaf5223 │             │        │ Europe/Warsaw │ 1       │ 0     │ 25 Aug 23 13:20:18 CEST │            │ RUNNING │                         │
╰─────────────────────────────────────────────┴─────────────┴────────┴───────────────┴─────────┴───────┴─────────────────────────┴────────────┴─────────┴─────────────────────────╯
```
Did you hit this issue consistently? I would suspect that the root cause of this issue wasn't direct bug in the implementation, but that it is a result of SM or Scylla being under increased pressure.

**Comment by karol-kokoszka** [comment] 2023-09-06 14:38
The only thing we can do here is to close this issue as "Cannot reproduce".
@vladzcloudius please deliver scylla manager logs when reporting this kind of bugs, otherwise it may be impossible to reproduce.

**Closed by karol-kokoszka** 2023-09-06 14:38 UTC
Labels: bug
